name: eo-env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python>=3.9
  - pip
  
  # Essential geospatial packages
  - rasterio>=1.3.0
  - geopandas>=0.10.0
  
  # Scientific computing
  - numpy>=1.20.0
  - matplotlib>=3.5.0
  
  # Additional dependencies
  - shapely>=1.8.0
  - fiona>=1.8.0